project_id = "novgdauuwrjvdgtqqqxj"

[functions.generate-template]
verify_jwt = false

[functions.generate-image-prompt]
verify_jwt = false

[functions.generate-ai-image]
verify_jwt = false

[functions.generate-motion-prompt]
verify_jwt = false

[functions.send-invite-request]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.get-billing-history]
verify_jwt = false

[functions.get-usage-analytics]
verify_jwt = false
